#![doc = include_str!("../README.md")]

use dis::ext::core::ContentIntoDisplayExt;
use dis::prelude_ext::{alloc::*, proc_macro2_diagnostics::*};
use dis::{MacroDeepResult, MacroDiagnosticResult, MacroStreamResult};

//use mce_lib::public::OwnedStringSlice;

use proc_macro::TokenStream as ProcTokenStream;
use proc_macro_rules::rules;
use proc_macro2::{Span, TokenStream};

use quote::quote_spanned;
use std::path::PathBuf;
use std::str::FromStr;
use std::sync::LazyLock;
use syn::{Expr, Ident, Path, Type};

mod file;

// @TODO
/*pub mod prelude {
    pub use crate::{def_let, def_let_direct, def_mut, def_mut_direct, def_const, def_const_direct, def_static, def_static_direct, at_let, at_mut, at_const, at_static};
}*/

/// Thanks to build.rs.
const OUT_DIR: &str = env!("OUT_DIR");

// Having an underscore in the literals/values, to make them more reasable.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum IdentNameConvention {
    LowerCase,
    UpperCase,
    CamelCase,
}
impl IdentNameConvention {
    const fn uses_underscore(&self) -> bool {
        matches!(*self, Self::LowerCase | Self::UpperCase)
    }

    /*fn can_apply_in_place(&self, s: &str, is_last_part: bool) -> bool {
        s.is_ascii() && !self.uses_underscore()
    }*/

    /// Apply formatting, including appending an underscore if this formatting involves it (and if
    /// `is_last_part` is `false`).
    fn apply(&self, mut s: String, is_last_part: bool) -> String {
        if let Some(new) = self.apply_or_new(&mut s, is_last_part) {
            new
        } else {
            s
        }
    }

    /// Apply formatting, including appending an underscore if this formatting involves it (and if
    /// `is_last_part` is `false`). Potentially modify the given slice, ad/or return [Some] of a new
    /// [String].
    /// - If returns [Some], use the return value. The given slice `s` _may_ be modified, but _not_
    ///   complete - so don't use it.
    /// - If returns [None], use the givene slice `s` - which may be modified (if due).
    fn apply_or_new(self, s: &mut str, is_last_part: bool) -> Option<String> {
        match self {
            IdentNameConvention::LowerCase | IdentNameConvention::UpperCase => {
                if s.is_ascii() && is_last_part {
                    match self {
                        IdentNameConvention::LowerCase => s.make_ascii_uppercase(),
                        IdentNameConvention::UpperCase => s.make_ascii_lowercase(),
                        IdentNameConvention::CamelCase => unreachable!(),
                    }
                    return None;
                } else {
                    let mut s = match self {
                        IdentNameConvention::LowerCase => s.to_uppercase(),
                        IdentNameConvention::UpperCase => s.to_lowercase(),
                        IdentNameConvention::CamelCase => unreachable!(),
                    };
                    if !is_last_part {
                        s.push('_');
                    }
                    return Some(s);
                }
            }
            IdentNameConvention::CamelCase => {
                if s.is_ascii() {
                    s.make_ascii_lowercase();
                    if s.len() > 0 {
                        let first = &mut s[0..1];
                        first.make_ascii_uppercase();
                    }
                    return None;
                } else {
                    let mut new = String::with_capacity(s.len());
                    let mut chars = s.chars();
                    if let Some(first) = chars.next() {
                        new.extend(first.to_uppercase());
                    }
                    new.extend(chars.map(|c| c.to_uppercase()).flatten());
                    return Some(new);
                }
            }
        }
    }
}

static OUT_DIR_LOWER_CASE: LazyLock<String> = LazyLock::new(|| {
    let s = OUT_DIR.to_owned();
    IdentNameConvention::LowerCase.apply(s, false)
});
static OUT_DIR_UPPER_CASE: LazyLock<String> = LazyLock::new(|| {
    let s = OUT_DIR.to_owned();
    IdentNameConvention::UpperCase.apply(s, false)
});
static OUT_DIR_CAMEL_CASE: LazyLock<String> = LazyLock::new(|| {
    let s = OUT_DIR.to_owned();
    IdentNameConvention::CamelCase.apply(s, false)
});
fn out_dir(convention: IdentNameConvention) -> &'static str {
    match convention {
        IdentNameConvention::LowerCase => &*OUT_DIR_LOWER_CASE,
        IdentNameConvention::UpperCase => &*OUT_DIR_UPPER_CASE,
        IdentNameConvention::CamelCase => &*OUT_DIR_CAMEL_CASE,
    }
}

static RND_PART_LOWER_CASE: LazyLock<String> = LazyLock::new(|| {
    let s = file::existing_rnd_part(OUT_DIR)
        .unwrap()
        .expect("Expecting a file generated by build.rs.");
    IdentNameConvention::LowerCase.apply(s, true)
});
static RND_PART_UPPER_CASE: LazyLock<String> = LazyLock::new(|| {
    let s = (*RND_PART_LOWER_CASE).clone();
    IdentNameConvention::UpperCase.apply(s, true)
});
static RND_PART_CAMEL_CASE: LazyLock<String> = LazyLock::new(|| {
    let s = (*RND_PART_LOWER_CASE).clone();
    IdentNameConvention::CamelCase.apply(s, true)
});
fn rnd_part(convention: IdentNameConvention) -> &'static str {
    match convention {
        IdentNameConvention::LowerCase => &*RND_PART_LOWER_CASE,
        IdentNameConvention::UpperCase => &*RND_PART_UPPER_CASE,
        IdentNameConvention::CamelCase => &*RND_PART_CAMEL_CASE,
    }
}

fn restricted_part(convention: IdentNameConvention) -> &'static str {
    match convention {
        IdentNameConvention::LowerCase => "restricted_",
        IdentNameConvention::UpperCase => "RESTRICTED_",
        IdentNameConvention::CamelCase => "Restricted",
    }
}

fn underscore_if_used(convention: IdentNameConvention) -> &'static str {
    if convention.uses_underscore() {
        "_"
    } else {
        ""
    }
}

struct LocalFilePath {
    local_path: PathBuf,
    convention: IdentNameConvention,
}
impl LocalFilePath {
    /// Create an instance. Convert any ASCII character sto lowercase/uppercase as indicated by
    /// `make_uppercase`.
    pub fn new(mut local_path: PathBuf, convention: IdentNameConvention) -> Self {
        Self {
            local_path,
            convention,
        }
    }
}

// Can't implement
// - `impl From<&LocalFilePath> for Option<&str>`, or
// - `impl Into<Option<&str>> for &LocalFilePath`
//
// because their lifetimes would have to be independent.
impl LocalFilePath {
    /// Get subpath, excluding any part shared with [OUT_DIR], and sanitize to be
    /// [Ident]-compatible.
    ///
    /// Do _not_ use for a last part of an identifier, because if [LocalFilePath::convention] part
    /// of `self` has [IdentNameConvention::uses_underscore] `true`, then this appends an underscore
    /// (which would then become a trailing underscore).
    ///
    // Just a subset of
    // https://rust-lang.github.io/rfcs/2457-non-ascii-idents.html#reference-level-explanation
    // (which refers to https://www.unicode.org/reports/tr31/).
    fn sanitize_as_ident_multi_part(&self) -> MacroDeepResult<String> {
        return if let Some(path) = self.local_path.to_str() {
            /*
            let s = if s.is_ascii() {
                // LocalFilePath::new() already converted any ASCII characters to
                // lowercase/uppercase as appropriate.
                owned_s = None;
                s
            } else {
                owned_s = Some(if self.convention {
                    s.to_uppercase()
                } else {
                    s.to_lowercase()
                });
                owned_s.as_ref().unwrap()
            };

            let out_dir = if self.convention {
                &(*OUT_DIR_UPPER_CASE)[..]
            } else {
                &(*OUT_DIR_LOWER_CASE)[..]
            };
            */

            let out_dir = out_dir(self.convention);

            let out_dir_chars_opt = out_dir
                .chars()
                .map(|c| Some(c))
                .chain(core::iter::repeat(None));
            let path_chars = path.chars();
            let mut pairs = path_chars.zip(out_dir_chars_opt);

            let mut num_same_chars_skipped = 0;
            loop {
                if let Some((p, Some(o))) = pairs.next()
                    && o == p
                {
                    num_same_chars_skipped += 1;
                    continue;
                } else {
                    break;
                }
            }

            let max_part_len = path.len() - num_same_chars_skipped;
            let mut joined_parts = String::with_capacity(max_part_len);
            {
                let mut part = String::with_capacity(max_part_len);

                let mut first_part_first_char = true;
                for (p, _) in pairs {
                    if first_part_first_char {
                        if p.is_alphabetic() {
                            part.push(p);
                            first_part_first_char = false;
                        }
                    } else {
                        if p.is_alphanumeric() {
                            part.push(p);
                        } else {
                            if part.len() > 0 {
                                part = self.convention.apply(part, false);
                                joined_parts.extend(part.chars());
                                part.clear();
                            }
                        }
                    }
                }
                if part.len() > 0 {
                    let part = self.convention.apply(part, false);
                    joined_parts.extend(part.chars());
                }
            }
            Ok(joined_parts)
        } else {
            Err(format!(
                "Source code file path contains non-UTF-8 byte(s). Lossy path: {}",
                self.local_path.to_string_lossy()
            )
            .into_dis()
            .as_macro_deep_diagnostic())
        };
    }
    /*let len = s.len().min(out_dir.len());
        let mut i = 0;
        while i < len {
            if s.as_bytes()[i] != out_dir.as_bytes()[i] {
                break;
            }
            i += 1;
        }
        // @TODO proper error
        assert!(
            i < s.len(),
            "Source of the macro crate that uses crate 'private' is at {s}, which should not under of OUT_DIR: {OUT_DIR}"
        );
        //OwnedStringSlice::new_starting_from(s, i)
        &s[i..]
    } else {
        return Err(format!(
            "Source code file path contains non-UTF-8 byte(s). Lossy path: {}",
            self.local_path.to_string_lossy()
        )
        .into_dis()
        .as_macro_deep_diagnostic());
    };

    let mut first_char = true;

    let filtered = path.chars().filter_map(|c| {
        if first_char {
            if c.is_alphabetic() {
                first_char = false;
                Some(c)
            } else {
                // Let's _not_ have the first character an underscore
                None
            }
        } else {
            if c.is_alphanumeric() {
                Some(c)
            } else {
                Some('_')
            }
        }
    });
    let mut s = String::with_capacity(path.len());
    s.extend(filtered);
    Ok(s)*/
}

fn local_file_path(
    span: Span,
    convention: IdentNameConvention,
) -> MacroDiagnosticResult<LocalFilePath> {
    if let Some(local_path) = span.local_file() {
        Ok(LocalFilePath::new(local_path, convention))
    } else {
        Err(format!(
            "Source file path unknown for code that invokes crate `reserved`. Span: {:?}",
            span
        )
        .to_error_at(span))
    }
}

/// Generate a full name. We do _not_ modify the part based on `ident_given_name` - so
/// `ident_given_name` already has to follow `convention`. However, we exclude any leading or
/// trailing underscores from `ident_given_name` - we do insert an underscore on each side of
/// `ident_given_name` if `convention` uses it.
///
/// Compatible with Rust non-ASCII identifiers
/// (https://rust-lang.github.io/rfcs/2457-non-ascii-idents.html).
fn restricted_full_name(
    ident_short_name: &Ident,
    convention: IdentNameConvention,
) -> MacroDiagnosticResult<Ident> {
    let span = ident_short_name.span();

    let file_path = local_file_path(span, convention)?;
    let ident_multi_part = file_path.sanitize_as_ident_multi_part().span_err(span)?;

    let restricted_part = restricted_part(convention);

    let underscore_if_used = underscore_if_used(convention);
    let rnd_part = rnd_part(convention);

    // Intentionally putting the random part at the end, to make errors/warnings more
    // obvious/searchable.

    // @TODO underscore - remove in CamelCase
    let full_name = format!(
        "{ident_multi_part}{restricted_part}{ident_short_name}{underscore_if_used}{rnd_part}"
    );

    Ok(Ident::new(&full_name, span))
}

#[proc_macro]
pub fn def_const(input: ProcTokenStream) -> ProcTokenStream {
    match def_const_or_static_grammar(input.into(), ItemChoice::Const, false) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
#[proc_macro]
pub fn def_const_direct(input: ProcTokenStream) -> ProcTokenStream {
    match def_const_or_static_grammar(input.into(), ItemChoice::Const, true) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
#[proc_macro]
pub fn def_static(input: ProcTokenStream) -> ProcTokenStream {
    match def_const_or_static_grammar(input.into(), ItemChoice::Static, false) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
#[proc_macro]
pub fn def_static_direct(input: ProcTokenStream) -> ProcTokenStream {
    match def_const_or_static_grammar(input.into(), ItemChoice::Static, true) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
// --------------

#[proc_macro]
pub fn at_const(input: ProcTokenStream) -> ProcTokenStream {
    match at_grammar(input.into(), ItemChoice::Const) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
#[proc_macro]
pub fn at_static(input: ProcTokenStream) -> ProcTokenStream {
    match at_grammar(input.into(), ItemChoice::Static) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
// --------------

/// Internal - not for direct use.
#[proc_macro]
#[doc(hidden)]
pub fn at_direct(input: ProcTokenStream) -> ProcTokenStream {
    match at_direct_grammar(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
// --------------

// @TODO generate code that
// 1. defines the let/mut/const
// 2. defines local (non-exported) macro_rules! local-variable-name-here
//    - BUT: if we do define (even just local) macro_rules! local-variable-name-here, then
//      - we definitely need to include $crate, to avoid conflicts; and
//      - worse: that consumer macro CANNOT be called multiple times in the same scope (conflicting
//        macro_rules!)
//      - without local macro_rules, that crate's macro(s) CAN be invoked multiple times in the same
//        scope, and any variables are shadowed.
//
// BUT: where/how do we include that consumer macro's $crate path? -> it would be HERE
//
//
// Either way: NOT for "re-entrant" macros. So we DON'T support macros usable like, or used like:
//
// custom_macro!( some-input-here... custom_macro!(...) ... )
//
// - unless the macro developer designed it so (that is, any expressions in the input would be
//   sub-scoped, like in a block {...}).
fn def_const_or_static_grammar(
    input: TokenStream,
    which: ItemChoice,
    direct: bool,
) -> MacroStreamResult {
    assert!(which == ItemChoice::Const || which == ItemChoice::Static);
    rules!(input => {
        ( $short_name:ident:$ty:ty = $value:expr ) => {
            def_const_static(which, short_name, ty, value, direct)
        }
    })
    .into()
}
/*macro_rules! _path_then_colon {
    ($path:path)
}*/

fn at_grammar(input: TokenStream, which: ItemChoice) -> MacroStreamResult {
    rules!(input => {
        ( $short_name:ident) => {
            at_impl(&short_name, which.convention())
        }
    })
}

fn at_direct_grammar(input: TokenStream) -> MacroStreamResult {
    Ok(rules!(input => {
        ( $short_name:ident, $full_name:ident, $tt:tt) => {
            let span = tt.span();
            // @TODO verify that full_name = short_name + tt.span
            quote_spanned! {span=>
                #full_name
            }
        }
    })
    .into())
}

/// Access choice for a var/value. For now (and hopefully forever) we ignore `static mut`.
#[derive(Clone, Copy, PartialEq, Eq)]
enum ItemChoice {
    Const,
    Static,
    Type,
    Fn,
}
impl ItemChoice {
    /// One of: `let`, `let mut`, `const`, `static`.
    pub fn keywords(&self) -> &'static str {
        match self {
            Self::Const => "const",
            Self::Static => "static",
            Self::Type => "type",
            Self::Fn => "fn",
        }
    }
    pub fn requires_type_and_value(&self) -> bool {
        self == &Self::Const || self == &Self::Static
    }

    pub fn convention(&self) -> IdentNameConvention {
        match self {
            Self::Const | Self::Static | Self::Fn => IdentNameConvention::LowerCase,
            Self::Type => IdentNameConvention::CamelCase,
        }
    }
}

fn def_const_static(
    which: ItemChoice,
    ident_short_name: Ident,
    ty: Type,
    value: Expr,
    direct: bool,
) -> MacroStreamResult {
    assert!(which == ItemChoice::Const || which == ItemChoice::Static);

    let full_name = restricted_full_name(&ident_short_name, which.convention())?;

    let span = ident_short_name.span();

    let const_static_let_mut_part = TokenStream::from_str(which.keywords())
        .map_err_to()
        .map_macro_err()
        .span_err(span)?;

    let type_part = quote_spanned! {span=>
        : #ty
    };
    let assign_part = quote_spanned! {span=>
        = #value
    };
    let direct_part = if direct {
        let doc = format!("(private) {ident_short_name} {type_part}");
        // #[doc = #doc] works to generate tooltip/mouseover with rust-analyzer:
        quote_spanned! {span=>
            #[doc = #doc]
            macro_rules! #ident_short_name {
                // @TODO require an input/parameter ----> span check
                ($tt:tt) => {
                    ::private::at_direct!(#ident_short_name, #full_name, $tt)
                    //#full_name
                }
            }
        }
    } else {
        TokenStream::new()
    };
    Ok(quote_spanned! {span=>
        #const_static_let_mut_part #full_name #type_part #assign_part;
        #direct_part
    })
}

fn at_impl(ident_short_name: &Ident, convention: IdentNameConvention) -> MacroStreamResult {
    let full_name = restricted_full_name(ident_short_name, convention)?;
    let span = ident_short_name.span();
    Ok(quote_spanned! {span=>
        #full_name
    })
}
