#![doc = include_str!("../README.md")]

use core::iter;
use dis::MacroStreamResult;
use dis::prelude_ext::{alloc::*, proc_macro2_diagnostics::*};

use proc_macro::TokenStream as ProcTokenStream;
use proc_macro_rules::rules;
use proc_macro2::TokenStream;

use quote::quote_spanned;
use std::str::FromStr;
use std::sync::LazyLock;
use syn::{Expr, Ident, Path, Type};

mod file;

/*pub mod prelude {
    pub use crate::{def_let, def_let_direct, def_mut, def_mut_direct, def_const, def_const_direct, def_static, def_static_direct, at_let, at_mut, at_const, at_static};
}*/

/// Thanks to build.rs.
const OUT_DIR: &str = env!("OUT_DIR");

static RND_PART_LOWERCASE: LazyLock<String> = LazyLock::new(|| {
    file::existing_rnd_part(OUT_DIR)
        .unwrap()
        .expect("Expecting a file generated by build.rs.")
});
static RND_PART_UPPERCASE: LazyLock<String> = LazyLock::new(|| {
    let mut value = (*RND_PART_LOWERCASE).clone();
    value.make_ascii_uppercase();
    value
});

fn to_upper_lower_case(mut s: String, should_be_uppercase: bool) -> String {
    if s.is_ascii() {
        if should_be_uppercase {
            s.make_ascii_uppercase();
        } else {
            s.make_ascii_lowercase();
        }
    } else {
        // These create a new String - that's OK.
        s = if should_be_uppercase {
            s.to_uppercase()
        } else {
            s.to_lowercase()
        };
    };
    s
}

// Compatible with Rust non-ASCII identifiers
// (https://rust-lang.github.io/rfcs/2457-non-ascii-idents.html).
fn var_or_const_or_static_name(
    macro_crate_and_path: Option<&Path>,
    given_name: &Ident,
    should_be_uppercase: bool,
) -> Ident {
    let path_based_prefix = if let Some(macro_crate_and_path) = macro_crate_and_path {
        // Either of the following two approaches leaves extra spaces around :: path separators:
        //
        // let mut path_based_prefix = macro_crate_and_path.into_token_stream().to_string();
        //
        // let mut path_based_prefix = quote!{ #macro_crate_and_path }.to_string();
        let iter = macro_crate_and_path.segments.iter();
        let mut parts = Vec::with_capacity(2 * iter.len());
        let mut total_len = 0;
        iter.for_each(|seg| {
            let ident = seg.ident.to_string();
            total_len += ident.len() + 1;
            parts.push(ident);
        });

        let mut path_based_prefix = String::with_capacity(total_len);
        path_based_prefix.extend(
            parts
                .iter()
                .map(|s| iter::once(&s[..]).chain(iter::once("_")))
                .flatten(),
        );

        /*if true { panic!("{}", path_based_prefix);}*/
        let path_based_prefix = to_upper_lower_case(path_based_prefix, should_be_uppercase);

        //let mut path_based_prefix = path_based_prefix.replace("::", "_"); // this creates a new String - that's OK.

        //path_based_prefix.push('_');
        Some(path_based_prefix)
    } else {
        None
    };
    let path_based_prefix = path_based_prefix.as_ref().map_or("", |rf| &rf);

    let private_ = if should_be_uppercase {
        "PRIVATE_"
    } else {
        "private_"
    };

    let span = given_name.span();
    let given_name = given_name.to_string();

    let rnd_part = if should_be_uppercase {
        &*RND_PART_UPPERCASE
    } else {
        &*RND_PART_LOWERCASE
    };

    // Intentionally putting the random part at the end, to make errors/warnings more
    // obvious/searchable.
    let full_name = format!("{path_based_prefix}{private_}{given_name}_{rnd_part}");

    Ident::new(&full_name, span)
}

#[proc_macro]
pub fn def_let(input: ProcTokenStream) -> ProcTokenStream {
    match def_let_or_mut_grammar(input.into(), ConstStaticLetMut::LET, false) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
#[proc_macro]
pub fn def_let_direct(input: ProcTokenStream) -> ProcTokenStream {
    match def_let_or_mut_grammar(input.into(), ConstStaticLetMut::LET, true) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
#[proc_macro]
pub fn def_mut(input: ProcTokenStream) -> ProcTokenStream {
    match def_let_or_mut_grammar(input.into(), ConstStaticLetMut::MUT, false) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
#[proc_macro]
pub fn def_mut_direct(input: ProcTokenStream) -> ProcTokenStream {
    match def_let_or_mut_grammar(input.into(), ConstStaticLetMut::MUT, true) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
#[proc_macro]
pub fn def_const(input: ProcTokenStream) -> ProcTokenStream {
    match def_const_or_static_grammar(input.into(), ConstStaticLetMut::CONST, false) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
#[proc_macro]
pub fn def_const_direct(input: ProcTokenStream) -> ProcTokenStream {
    match def_const_or_static_grammar(input.into(), ConstStaticLetMut::CONST, true) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
#[proc_macro]
pub fn def_static(input: ProcTokenStream) -> ProcTokenStream {
    match def_const_or_static_grammar(input.into(), ConstStaticLetMut::STATIC, false) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
#[proc_macro]
pub fn def_static_direct(input: ProcTokenStream) -> ProcTokenStream {
    match def_const_or_static_grammar(input.into(), ConstStaticLetMut::STATIC, true) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}

// @TODO consider names: handle, get
#[proc_macro]
pub fn at_let(input: ProcTokenStream) -> ProcTokenStream {
    match at_grammar(input.into(), ConstStaticLetMut::LET) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
#[proc_macro]
pub fn at_mut(input: ProcTokenStream) -> ProcTokenStream {
    match at_grammar(input.into(), ConstStaticLetMut::MUT) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
#[proc_macro]
pub fn at_const(input: ProcTokenStream) -> ProcTokenStream {
    match at_grammar(input.into(), ConstStaticLetMut::CONST) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
#[proc_macro]
pub fn at_static(input: ProcTokenStream) -> ProcTokenStream {
    match at_grammar(input.into(), ConstStaticLetMut::STATIC) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}

/*
#[proc_macro]
pub fn def_mut(input: ProcTokenStream) -> ProcTokenStream {
    match def_mut_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}

#[proc_macro]
pub fn def_const(input: ProcTokenStream) -> ProcTokenStream {
    match def_const_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}

#[proc_macro]
pub fn use_let(input: ProcTokenStream) -> ProcTokenStream {
    match use_let_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}

#[proc_macro]
pub fn use_mut(input: ProcTokenStream) -> ProcTokenStream {
    match use_mut_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}

#[proc_macro]
pub fn use_const(input: ProcTokenStream) -> ProcTokenStream {
    match use_const_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}*/
// --------------

// @TODO generate code that
// 1. defines the let/mut/const
// 2. defines local (non-exported) macro_rules! local-variable-name-here
//    - BUT: if we do define (even just local) macro_rules! local-variable-name-here, then
//      - we definitely need to include $crate, to avoid conflicts; and
//      - worse: that consumer macro CANNOT be called multiple times in the same scope (conflicting
//        macro_rules!)
//      - without local macro_rules, that crate's macro(s) CAN be invoked multiple times in the same
//        scope, and any variables are shadowed.
//
// BUT: where/how do we include that consumer macro's $crate path? -> it would be HERE
//
//
// Either way: NOT for "re-entrant" macros. So we DON'T support macros usable like, or used like:
//
// custom_macro!( some-input-here... custom_macro!(...) ... )
//
// - unless the macro developer designed it so (that is, any expressions in the input would be
//   sub-scoped, like in a block {...}).
fn def_let_or_mut_grammar(
    input: TokenStream,
    which: ConstStaticLetMut,
    direct: bool,
) -> MacroStreamResult {
    assert!(which == ConstStaticLetMut::LET || which == ConstStaticLetMut::MUT);
    rules!(input => {
        ( $name:ident = $value:expr) => {
            def_const_static_let_mut(which, &name, None, None, Some(&value), direct)
        }
        ( $name:ident @$path:path = $value:expr ) => {
            def_const_static_let_mut(which, &name, Some(&path), None, Some(&value), direct)
        }

        ( $name:ident: $ty:ty = $value:expr ) => {
            def_const_static_let_mut(which, &name, None, Some(&ty), Some(&value), direct)
        }
        ( $name:ident @$path:path :$ty:ty = $value:expr ) => {
            def_const_static_let_mut(which, &name, Some(&path), Some(&ty), Some(&value), direct)
        }

        ( $name:ident ) => {
            def_const_static_let_mut(which, &name, None, None, None, direct)
        }
        ( $name:ident @ $path:path) => {
            def_const_static_let_mut(which, &name, Some(&path), None, None, direct)
        }

        ( $name:ident : $ty:ty ) => {
            def_const_static_let_mut(which, &name, None, Some(&ty), None, direct)
        }
        ( $name:ident @$path:path :$ty:ty ) => {
            def_const_static_let_mut(which, &name, Some(&path), Some(&ty), None, direct)
        }
    })
    .into()
}
fn def_const_or_static_grammar(
    input: TokenStream,
    which: ConstStaticLetMut,
    direct: bool,
) -> MacroStreamResult {
    assert!(which == ConstStaticLetMut::CONST || which == ConstStaticLetMut::STATIC);
    rules!(input => {
        ( $name:ident:$ty:ty = $value:expr ) => {
            def_const_static_let_mut(which, &name, None, Some(&ty), Some(&value), direct)
        }
        ( $name:ident@$path:path:$ty:ty = $value:expr ) => {
            def_const_static_let_mut(which, &name, Some(&path), Some(&ty), Some(&value), direct)
        }
    })
    .into()
}
/*macro_rules! _path_then_colon {
    ($path:path)
}*/

fn at_grammar(input: TokenStream, which: ConstStaticLetMut) -> MacroStreamResult {
    Ok(rules!(input => {
        ( $name:ident) => {
            at_impl(&name, None, which.requires_type_and_value_and_should_be_uppercase())
        }
        ( $name:ident@$path:path) => {
            at_impl(&name, Some(&path), which.requires_type_and_value_and_should_be_uppercase())
        }
    })
    .into())
}

/// Access choice for a var/value. For now (and hopefully forever) we ignore `static mut`.
#[derive(Clone, Copy, PartialEq, Eq)]
enum ConstStaticLetMut {
    CONST,
    STATIC,
    LET,
    MUT,
}
impl ConstStaticLetMut {
    /// One of: `let`, `let mut`, `const`, `static`.
    pub fn keywords(&self) -> &'static str {
        match self {
            Self::CONST => "const",
            Self::STATIC => "static",
            Self::LET => "let",
            Self::MUT => "let mut",
        }
    }
    pub fn requires_type_and_value_and_should_be_uppercase(&self) -> bool {
        self == &Self::CONST || self == &Self::STATIC
    }
}

fn def_const_static_let_mut(
    which: ConstStaticLetMut,
    name: &Ident,
    path: Option<&Path>,
    ty: Option<&Type>,
    value: Option<&Expr>,
    direct: bool,
) -> MacroStreamResult {
    assert!(!which.requires_type_and_value_and_should_be_uppercase() || ty.is_some());
    assert!(!which.requires_type_and_value_and_should_be_uppercase() || value.is_some());

    let var_name = var_or_const_or_static_name(
        path,
        name,
        which.requires_type_and_value_and_should_be_uppercase(),
    );

    let span = name.span();

    let const_static_let_mut_part = TokenStream::from_str(which.keywords())
        .map_err_to()
        .map_macro_err()
        .span_err(span)?;

    let type_part = if let Some(ty) = ty {
        quote_spanned! {span=>
            : #ty
        }
    } else {
        TokenStream::new()
    };
    let assign_part = if let Some(value) = value {
        quote_spanned! {span=>
            = #value
        }
    } else {
        TokenStream::new()
    };
    let direct_part = if direct {
        let doc = format!("(private) {name} {type_part}");
        quote_spanned! {span=>
            // This works to generate tooltip/mouseover with rust-analyzer:
            #[doc = #doc]
            macro_rules! #name {
                () => {
                    #var_name
                }
            }
        }
    } else {
        TokenStream::new()
    };
    Ok(quote_spanned! {span=>
        #const_static_let_mut_part #var_name #type_part #assign_part;
        #direct_part
    })
}

fn at_impl(name: &Ident, path: Option<&Path>, should_be_uppercase: bool) -> TokenStream {
    let var_name = var_or_const_or_static_name(path, name, should_be_uppercase);
    let span = name.span();
    quote_spanned! {span=>
        #var_name
    }
}
